### PR TITLE
Correctly set account start nonce upon chainparams creation.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes morden consensus.

### CODE REVIEW

**Comment by chriseth** [comment]
It seems this is not yet the full fix, cannot sync beyond 323, I would assume 324 contains the first transaction from an account that is not part of the genesis block and that account has an invalid start nonce (morden has a start nonce of != 0).

**Comment by chriseth** [comment]
Oh and I have seen a commit in an ethcore repo that was not propagated upwards that changed a default constructor - that might be the fix.

**Comment by bobsummerwill** [comment]
Just for my understanding, @chriseth, so the issue here is that we were implicitly dependent on the fact that the nonce for the genesis block was 0, which is true for the mainnet, but false for Morden.

Is this a consensus bug something new which only affects post-Homestead blocks?

What would that nonce be for other arbitrary private networks?

**Comment by chriseth** [comment]
@bobsummerwill the nonce is only different for morden to avoid replay attacks between the networks. As far as I can tell, morden never worked in c++, a lot of changes connected to the start nonce were just not implemented.

**Comment by bobsummerwill** [comment]
Gotcha.   Thanks for the info.

I guess, thinking back, that I have always used geth on the handful of occasions where I have used Morden (including on the Gear S2 smartwatch!)

**Pull request merged**
