### PR TITLE
fix segfault when typing web3 into the eth console

### PR DESCRIPTION
**Pull request by winsvega**

### CODE REVIEW

**Comment by chriseth** [comment]
Are you sure this was the reason? I think you introduced a bug by that change (you skipped one value).

**Comment by winsvega** [comment]
which value?
web3 command works for me with this change.

**Comment by chriseth** [comment]
In the else-case, you first increment `i` and then access `i->second.first`. Before your change, it was accessing `i->second.first` before the increment (keep in mind that it used the post-increment and not the pre-increment operator).

**Comment by chriseth** [comment]
I don't see a semantic change here. If size is zero, then begin should be equal to end and the loop is skipped. On the other hand, if begin is equal to end, size is zero.

**Comment by winsvega** [comment]
what might be the case here? maybe keyword mutable makes this variable vulnerable to changes where it is not needed? 

however if I remove size check it will throw segfault when trying to execute boost add:
ret += i++->second.first;

**Comment by chriseth** [comment]
If the error is really here, then it might be due to heap corruption or a threading issue.

**Comment by winsvega** [comment]
then just checking out size would not be a perfect solution.

**Pull request closed without merging**
