### PR TITLE
additional uncle header validity tests

### PR DESCRIPTION
**Pull request by winsvega**
connects to https://github.com/ethereum/webthree-umbrella/issues/418

### CODE REVIEW

**Comment by chriseth** [comment]
Test failures. Are they related?

**Comment by chriseth** [comment]
Are the test failures related?

**Comment by winsvega** [comment]
I can't get which test is failing. the console log shows that everything is ok. 
but it looks like 2 tests fails in BlockChainSuite. 
changes in this PR are for BlockChainTests so they are not related and not consensus ones. 
but those one which gives us head ake - I can't reproduce it locally.

**Comment by bobsummerwill** [comment]
Could you poke this again, please @winsvega, so we can see if these tests are now running cleanly in Jenkins?   Thanks!

**Comment by winsvega** [comment]
hm. windows build hangs

**Comment by bobsummerwill** [comment]
Are you going to "poke these", @winsvega?

**Comment by winsvega** [comment]
I did this several times already

**Pull request merged**
