### PR TITLE
Sync over PV62

### PR DESCRIPTION
**Pull request by arkpar**
This includes new parallel sync over pv62
Still left to do:
- Fast sync over pv63
- Review security and attack vectors from security audit report

DEPENDS:
{
"alethzero":"pv63"
}

### CODE REVIEW

**Comment by LefterisJP** [comment]
Nice usage of the depends feature @arkpar  :+1:

**Comment by chriseth** [comment]
@arkpar @chfast can you please tell me the state of this pull request?

**Comment by chriseth** [comment]
Runtime error: `./alethzero/alethzero/alethzero: symbol lookup error: ./alethzero/alethzero/alethzero: undefined symbol: _ZNK3dev3eth6Client11downloadManEv` (might be resolved by clean build)

**Comment by chriseth** [comment]
Continued in #155

**Pull request closed without merging**
