### PR TITLE
Take transactions from postSeal.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by winsvega** [comment]
have you tested it with pending transactions?

**Comment by chriseth** [comment]
No, but it works fine with the solidity tests, because we do not yet use that feature. Perhaps you could write some tests in javascript using ethereum-console?

**Comment by winsvega** [comment]
I could create one using solidity test ipcsocket

**Comment by chriseth** [comment]
Solidity's ipcsocket will not be available for a test for libethereum and we have quite some javascript tests already (they are just not run).

**Comment by winsvega** [comment]
I mean I could test modifytimestamp feature from solidity hardcoded test using IPC socket.
where are the javascript tests?

**Pull request merged**
