### PR TITLE
Travis CI: whitelist only master and develop branches

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Where is the other build coming from, @chfast?
You did mention this elsewhere, but I have forgotten the specifics.

**Comment by chfast** [comment]
Travis has 2 build triggers: push and pr. If you pushed a branch "example-feature" to libethereum repo it would trigger both.

**Comment by chfast** [comment]
See https://github.com/ethereum/libethereum/pull/301

**Comment by bobsummerwill** [comment]
Thanks for the info.   Yeah - that makes total sense now.

**Pull request merged**
