### PR TITLE
Move OverlayDB.cpp/.h from libdevcrypto to libdevcore.

### PR DESCRIPTION
**Pull request by fossilet**
This PR is part of ethereum/webthree-umbrella#146.

DEPENDS:
{
  "libweb3core": "develop"
}

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Hey @fossilet!
Looks like you're missing the metadata in your first comment, so that this automation uses the matching commit of libweb3core.   Do you understand how to do that?

**Comment by fossilet** [comment]
@bobsummerwill I added the DEPENDS metadata. Is that correct?

**Comment by bobsummerwill** [comment]
I've not done it myself, but I think it looks wrong to me, because you need it to point to your PR, don't you, not "develop".

**Comment by chriseth** [comment]
Yes, it should be the name of the branch in your github fork. But don't mind the hassle, I'll build it locally once and merge afterwards.

**Comment by fossilet** [comment]
@chriseth thank you for your help.

As the [CI wiki page](https://github.com/ethereum/webthree-umbrella/wiki/Continuous-Integration) reads, I need to specify the branch name of the my fork, which is develop, but I do not know why it still does not work.

**Comment by bobsummerwill** [comment]
Thanks, @fossilet and @chriseth!

**Pull request merged**
