### PR TITLE
Guard threaded access of the hashrate.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/webthree-umbrella/issues/188 and https://github.com/ethereum/webthree-umbrella/issues/113

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Simple change.   Looks good to me.
Were you able to replicate the issue and verify the fix at runtime, @chriseth?

**Comment by chriseth** [comment]
@bobsummerwill I have seen the issue at some point in the past, I did not verify the fix, but it is obvious that we need a lock here, as `submitExternalHashrate` is called from the json-rpc-thread and `hashrate` is called from the UI thread.

If we have time, we could perhaps disentangle threaded access somehow...

**Comment by smartbitcoin** [comment]
As the talk between  Chris and me , the issue come from the improper casting in EthashClient.cpp. Add a lock wont help this case.

**Comment by chriseth** [comment]
The real fix will be in https://github.com/ethereum/webthree/pull/106

**Pull request merged**
