### PR TITLE
Multiple BALANCE instruction call test

### PR DESCRIPTION
**Pull request by winsvega**

### CODE REVIEW

**Comment by chriseth** [comment]
What is the purpose of this test? Why did the test run fail?

**Comment by winsvega** [comment]
test run fails due to some other reason (Jenkins)
Paweł Bylica @chfast  asked for this tests
never have enough of them :)

**Comment by chriseth** [comment]
@winsvega please still explain what it does.

**Comment by winsvega** [comment]
Pawel wanted a test in which BALANCE instruction is being called at least twice during one call.

**Comment by chfast** [comment]
I needed such test.

**Comment by chfast** [comment]
@chriseth any objections? can we merge it?

**Pull request merged**
