### PR TITLE
changed default gas price

### PR DESCRIPTION
**Pull request by LianaHus**
todo: fixe tests

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Looks good.    Do you know why the tests are failing?    I still don't really understand how to read the output text.

**Comment by LianaHus** [comment]
yes, golden output changed. will push commit soon.

**Comment by LianaHus** [comment]
@winsvega could you please look at this PR?

**Comment by winsvega** [comment]
test run should not fail due to the 40 minutes execution time. something is wrong at gaspricer tests. this PR depends on another gasPricer PR's right?  
It is expected to have regular BOOST_REQUIRE error in tests. Could you trigger another build?

**Pull request closed without merging**
