### PR TITLE
use singletest option to specify test file name in stRandom tests

### PR DESCRIPTION
**Pull request by winsvega**
Bob is currently debuggin StateTests and for randomTests this option should choose test by it's filename not by the testname inside a file

### CODE REVIEW

**Comment by gcolvin** [comment]
This still works as it used to, but I can't seem to run just one stRandom test.  Maybe I have the syntax wrong, but removing the _.json_ didn't help.

```
gcolvin@Dell:~/ether/w3u/build/libethereum/test$ ./testeth --verbosity 2 -t StateTests/stBoundsTestHomestead --singletest BLOCKHASH_Bounds
Running 1 test case...
  ℹ  15:07:31.275|testeth  TEST stBoundsTest :
Test Case "stBoundsTestHomestead": 
  ℹ  15:07:31.279|testeth  BLOCKHASH_Bounds
23%...
46%...
69%...
93%...
100%

*** No errors detected
gcolvin@Dell:~/ether/w3u/build/libethereum/test$ ./testeth --verbosity 2 -t StateTests/stRandom --singletest st201504081842JAVA.json
Running 1 test case...
Test Case "stRandom": 
  ℹ  15:07:46.405|testeth  Testing ... "st201503181226CPPJIT.json"
  ℹ  15:07:46.405|testeth  Testing ... "st201503122324GO.json"
  ℹ  15:07:46.405|testeth  Testing ... "st201504091403CPPJIT.json"
  ℹ  15:07:46.405|testeth  Testing ... "st201503181235CPPJIT.json"
  ℹ  15:07:46.405|testeth  Testing ... "st201503181724GO.json"
  ℹ  15:07:46.405|testeth  Testing ... "st201503181548CPPJIT.json"
  ℹ  15:07:46.405|testeth  Testing ... "st201503181629GO.json"
  ℹ  15:07:46.406|testeth  Testing ... "st201503181315GO.json"
  ℹ  15:07:46.406|testeth  Testing ... "st201503181703CPPJIT.json"
  ℹ  15:07:46.406|testeth  Testing ... "st201504021057JS.json"
  ℹ  15:07:46.406|testeth  Testing ... "st201503181720CPPJIT.json"
  ℹ  15:07:46.406|testeth  Testing ... "st201504240817CPPJIT.json"
  ℹ  15:07:46.406|testeth  Testing ... "st201503181534GO.json"
  ℹ  15:07:46.406|testeth  Testing ... "st201505052102JS.json"
  ℹ  15:07:46.406|testeth  Testing ... "st201503181747GO.json"
  ℹ  15:07:46.407|testeth  Testing ... "st201503130122GO.json"
  ℹ  15:07:46.407|testeth  Testing ... "st201504042052JS.json"
  ℹ  15:07:46.407|testeth  Testing ... "st201503181715GO.json"
  ℹ  15:07:46.407|testeth  Testing ... "st201503181703GO.json"
  ℹ  15:07:46.407|testeth  Testing ... "st201504092303CPPJIT.json"
  ℹ  15:07:46.407|testeth  Testing ... "st201503181922GO.json"
  ℹ  15:07:46.407|testeth  Testing ... "st201503181755GO.json"
  ℹ  15:07:46.407|testeth  Testing ... "st201503181824GO.json"
  ℹ  15:07:46.408|testeth  Testing ... "st201503181252CPPJIT.json"
  ℹ  15:07:46.408|testeth  Testing ... "st201503181439CPPJIT.json"
  ℹ  15:07:46.408|testeth  Testing ... "st201503121806PYTHON.json"
  ℹ  15:07:46.408|testeth  Testing ... "st201503181453GO.json"
  ℹ  15:07:46.408|testeth  Testing ... "st201503181358CPPJIT.json"
  ℹ  15:07:46.408|testeth  Testing ... "st201503170523PYTHON.json"
  ℹ  15:07:46.408|testeth  Testing ... "st201503181506CPPJIT.json"
  ℹ  15:07:46.408|testeth  Testing ... "st201503181625GO.json"
  ℹ  15:07:46.409|testeth  Testing ... "st201503122124GO.json"
  ℹ  15:07:46.409|testeth  Testing ... "st201503181303GO.json"
  ℹ  15:07:46.409|testeth  Testing ... "st201503181435GO.json"
  ℹ  15:07:46.409|testeth  Testing ... "st201504131821CPPJIT.json"
  ℹ  15:07:46.409|testeth  Testing ... "st201503181754CPPJIT.json"
  ℹ  15:07:46.409|testeth  Testing ... "st201503181234GO.json"
  ℹ  15:07:46.409|testeth  Testing ... "st201503181347GO.json"
  ℹ  15:07:46.409|testeth  Testing ... "st201504101223CPPJIT.json"
  ℹ  15:07:46.410|testeth  Testing ... "st201503181301CPPJIT.json"
  ℹ  15:07:46.410|testeth  Testing ... "st201505060120GO.json"
  ℹ  15:07:46.410|testeth  Testing ... "st201504210957CPPJIT.json"
  ℹ  15:07:46.410|testeth  Testing ... "st201503181743GO.json"
  ℹ  15:07:46.410|testeth  Testing ... "st201506070548GO.json"
  ℹ  15:07:46.410|testeth  Testing ... "st201504011916JS.json"
  ℹ  15:07:46.410|testeth  Testing ... "st201503181325GO.json"
  ℹ  15:07:46.410|testeth  Testing ... "st201503181658GO.json"
  ℹ  15:07:46.411|testeth  Testing ... "st201503181245GO.json"
  ℹ  15:07:46.411|testeth  Testing ... "st201503130207GO.json"
  ℹ  15:07:46.411|testeth  Testing ... "st201503181330GO.json"
  ℹ  15:07:46.411|testeth  Testing ... "st201503181531CPPJIT.json"
  ℹ  15:07:46.411|testeth  Testing ... "st201506060929GO.json"
  ℹ  15:07:46.411|testeth  Testing ... "st201503181255CPPJIT.json"
  ℹ  15:07:46.412|testeth  Testing ... "st201503181734GO.json"
  ℹ  15:07:46.412|testeth  Testing ... "st201503181438CPPJIT.json"
  ℹ  15:07:46.412|testeth  Testing ... "st201503181410GO.json"
  ℹ  15:07:46.412|testeth  Testing ... "st201503181716GO.json"
  ℹ  15:07:46.412|testeth  Testing ... "st201503181323CPPJIT.json"
  ℹ  15:07:46.412|testeth  Testing ... "st201503181630PYTHON.json"
  ℹ  15:07:46.414|testeth  Testing ... "st201503181232CPPJIT.json"
  ℹ  15:07:46.414|testeth  Testing ... "st201504061134CPPJIT.json"
  ℹ  15:07:46.414|testeth  Testing ... "st201505272131CPPJIT.json"
  ℹ  15:07:46.414|testeth  Testing ... "st201503181304GO.json"
  ℹ  15:07:46.414|testeth  Testing ... "st201503181737CPPJIT.json"
  ℹ  15:07:46.415|testeth  Testing ... "st201503122023PYTHON.json"
  ℹ  15:07:46.415|testeth  Testing ... "st201503181910GO.json"
  ℹ  15:07:46.415|testeth  Testing ... "st201504020836JS.json"
  ℹ  15:07:46.415|testeth  Testing ... "st201504081957JAVA.json"
  ℹ  15:07:46.415|testeth  Testing ... "st201503181639CPPJIT.json"
  ℹ  15:07:46.415|testeth  Testing ... "st201505051249GO.json"
  ℹ  15:07:46.415|testeth  Testing ... "st201503181729GO.json"
  ℹ  15:07:46.415|testeth  Testing ... "st201503181745CPPJIT.json"
  ℹ  15:07:46.415|testeth  Testing ... "st201503130243GO.json"
  ℹ  15:07:46.416|testeth  Testing ... "st201503121953GO.json"
  ℹ  15:07:46.416|testeth  Testing ... "st201503130332GO.json"
  ℹ  15:07:46.416|testeth  Testing ... "st201503181816CPPJIT.json"
  ℹ  15:07:46.416|testeth  Testing ... "st201503181230GO.json"
  ℹ  15:07:46.416|testeth  Testing ... "st201503181730GO.json"
  ℹ  15:07:46.416|testeth  Testing ... "st201503181528PYTHON.json"
  ℹ  15:07:46.417|testeth  Testing ... "st201503181755CPPJIT.json"
  ℹ  15:07:46.418|testeth  Testing ... "st201503181842GO.json"
  ℹ  15:07:46.418|testeth  Testing ... "st201504082000JAVA.json"
  ℹ  15:07:46.418|testeth  Testing ... "st201504081842JAVA.json"
  ℹ  15:07:46.418|testeth  randomStatetest
*** Error in `./testeth': double free or corruption (!prev): 0x00000000024b6180 ***
unknown location(0): fatal error in "stRandom": signal: SIGABRT (application abort requested)
/home/gcolvin/ether/w3u/libethereum/test/TestHelper.cpp(276): last checkpoint

*** 1 failure detected in test suite "Master Test Suite"
```

**Comment by winsvega** [comment]
use -singletest `<randomtestfilename>`

**Comment by gcolvin** [comment]
But isn't that what I'm doing?  (Asks a sleepy, myopic old man.)  Do I need the actual path to the json file?  I'll try that.

`./testeth --verbosity 2 -t StateTests/stRandom --singletest st201504081842JAVA.json`

**Comment by gcolvin** [comment]
That didn't help.  I'm probably already asleep and completely blind...

**Comment by bobsummerwill** [comment]
What's happening with this one, @winsvega?
Who's waiting for who? :-)

**Comment by gcolvin** [comment]
@bobsummerwill Dmitry is waiting for me to test it, but I'm busy rewriting the code that exercised the test. If Dmitry is happy with it we should just check it in, as the rewrite is turning into a thorough redesign.

**Comment by bobsummerwill** [comment]
I'll leave you guys to it then!

**Pull request merged**
