### PR TITLE
BlockChainTests refactoring

### PR DESCRIPTION
**Pull request by winsvega**

### CODE REVIEW

**Comment by CJentzsch** [comment]
Is there any difference to https://github.com/ethereum/cpp-ethereum/pull/2868 ? 
(The number of lines added/removed have a mismatch of one line)

**Comment by winsvega** [comment]
I just copied.

it is JsonSpiritHeaders include in testHelper.h

**Comment by CJentzsch** [comment]
looks good

**Comment by winsvega** [comment]
updated branch https://github.com/ethereum/libethereum/pull/8

**Pull request closed without merging**
